import { Controller, Get } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

@Controller()
export class LegalController {
  constructor(private readonly configService: ConfigService) {}

  @Get('privacy')
  getPrivacyPolicy() {
    const appUrl = this.configService.get<string>('app.url');
    return {
      title: 'Privacy Policy',
      lastUpdated: '2024-01-01',
      appName: 'CopyAI — AI Product Copywriter',
      content: {
        introduction: `CopyAI ("we", "our", or "us") is a Shopify application that uses artificial intelligence to help store owners generate and improve product copy. This Privacy Policy explains how we collect, use, and protect your information when you install and use our app.`,
        dataCollected: [
          'Shopify store domain and basic shop information (name, email, currency, timezone)',
          'Product titles and descriptions from your store (only when you explicitly request rewrites)',
          'Usage statistics (number of rewrites performed, plan type)',
          'Billing and subscription information (managed via Shopify Billing API)',
        ],
        dataUsage: [
          'To provide AI-powered product description rewrites, email copy, and ad copy generation',
          'To manage your subscription and enforce plan limits',
          'To improve our AI prompts and service quality',
          'To send transactional communications related to your account',
        ],
        dataSharing: `We share your product data with Anthropic (Claude AI) solely to generate the requested copy. We do not sell your data to third parties. Product data sent to the AI is not used to train AI models per our agreements with AI providers.`,
        dataRetention: `We retain your shop data for as long as you have the app installed. Job history (rewrite records) is retained for 90 days. You may request deletion of all data by uninstalling the app and contacting us.`,
        security: `All data is transmitted over HTTPS. Access tokens are stored encrypted. We follow Shopify's security best practices and Partner Program requirements.`,
        merchantRights: `You may request a copy of your data, correction of inaccurate data, or deletion of your data at any time by contacting us. Uninstalling the app will deactivate your account and stop all data processing.`,
        contact: `For privacy-related questions, contact us at privacy@copyai.app`,
        shopifyCompliance: `This app complies with Shopify's Partner Program Agreement and API Terms of Service. We only request the minimum scopes necessary: read_products and write_products.`,
      },
    };
  }

  @Get('terms')
  getTermsOfService() {
    const appUrl = this.configService.get<string>('app.url');
    return {
      title: 'Terms of Service',
      lastUpdated: '2024-01-01',
      appName: 'CopyAI — AI Product Copywriter',
      content: {
        acceptance: `By installing CopyAI, you agree to these Terms of Service. If you do not agree, please uninstall the app.`,
        service: `CopyAI provides AI-generated product descriptions, email copy, and ad copy for Shopify stores. Content is generated by AI and may require review before publishing. We do not guarantee specific conversion outcomes.`,
        usage: [
          'You are responsible for reviewing AI-generated content before publishing to your store',
          'You may not use the app to generate misleading, harmful, or illegal content',
          'You may not attempt to reverse-engineer or abuse the API rate limits',
          'Fair use: plan limits are per store per billing cycle',
        ],
        billing: `Paid plans are billed through Shopify Billing. Charges appear on your Shopify invoice. Cancellation takes effect at the end of the current billing cycle. No refunds are provided for partial billing periods.`,
        aiContent: `AI-generated content is provided as-is. We do not warrant that generated content is original, accurate, or free from errors. You retain ownership of all content generated for your store.`,
        limitation: `Our liability is limited to the amount you paid to us in the 30 days prior to any claim. We are not liable for indirect, incidental, or consequential damages.`,
        termination: `We may suspend or terminate access if you violate these terms or Shopify's policies. You may terminate by uninstalling the app at any time.`,
        changes: `We may update these terms. Continued use after changes constitutes acceptance.`,
        contact: `Questions? Contact us at support@copyai.app`,
      },
    };
  }

  @Get('support')
  getSupportInfo() {
    return {
      email: 'support@copyai.app',
      responseTime: 'Within 24 hours on business days',
      documentation: 'Available in the app dashboard under Help',
      commonIssues: [
        { issue: 'App not loading', solution: 'Try clearing browser cache or re-installing the app' },
        { issue: 'AI not generating content', solution: 'Ensure your product description has at least some text to work with' },
        { issue: 'Billing questions', solution: 'Contact Shopify support or email us at billing@copyai.app' },
      ],
    };
  }
}
